# Generated by Django 4.2.5 on 2023-09-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySummoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('ladder_rank', models.IntegerField(default=0)),
                ('ladder_rank_percentage', models.IntegerField(verbose_name=0)),
            ],
        ),
    ]
